# Use the official Nginx base image
FROM nginx:latest

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/

# Copy your frontend build files into the Nginx HTML directory
COPY build /usr/share/nginx/html

# Expose the port Nginx will listen on
EXPOSE 8080

# Start Nginx when the container is run
CMD ["nginx", "-g", "daemon off;"]
